apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dicerolls.example.com
spec:
  group: example.com
  scope: Namespaced
  names:
    plural: dicerolls
    singular: diceroll
    kind: DiceRoll
    shortNames:
    - dr
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              dice:
                type: array
                items:
                  type: string
                  enum:
                  - D4
                  - D6
                  - D8
                  - D10
                  - D12
                  - D20
                  - D100
                description: List of dice to roll
          status:
            type: object
            properties:
              total:
                type: integer
                description: Sum of the results
              results:
                type: array
                description: Results of the individual rolls
                items:
                  type: object
                  properties:
                    die:
                      type: string
                      description: The die that was rolled
                    value:
                      type: integer
                      description: The value of the roll
