apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dicerolls.example.com
spec:
  group: example.com
  scope: Namespaced
  names:
    plural: dicerolls
    singular: diceroll
    kind: DiceRoll
    shortNames:
    - dr
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              dice:
                type: array
                items:
                  type: string
                description: List of D&D dice to roll
              modifier:
                type: integer
                description: Modifier to add to the result
          status:
            type: object
            properties:
              result:
                type: integer
                description: Result of the dice roll
