apiVersion: v1
kind: ServiceAccount
metadata:
  name: dice-roll-operator

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dice-roll-operator
rules:
- apiGroups:
  - example.com
  resources:
  - dicerolls
  - dicerolls/status
  verbs:
  - get
  - watch
  - list
  - create
  - update
  - patch
  - delete

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dice-roll-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dice-roll-operator
subjects:
- kind: ServiceAccount
  name: dice-roll-operator
  namespace: default

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dice-roll-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dice-roll-operator
  template:
    metadata:
      labels:
        app: dice-roll-operator
    spec:
      serviceAccountName: dice-roll-operator
      containers:
      - name: dice-roll-operator
        image: dice-roll-operator:1.0.0
