services:
  server:
    build: ./Simplenetes.Server
    ports:
      - "5000:5000"
    depends_on:
      - database

  controller:
    build: ./Simplenetes.Controller
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

  database:
    image: postgres:16.2
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: simplenetes
    volumes:
    - type: bind
      source: ./setup.sql
      target: /docker-entrypoint-initdb.d/setup.sql
    ports:
      - "5432:5432"
